name: climbing
description: Application allowing to give a feedback to climbing route setters.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter_rating_bar: 3.0.1+1
  shared_preferences: ^2.0.6
  cached_network_image: ^3.1.0
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.5
  vibrate: ^0.0.4
  apple_sign_in: ^0.1.0
  #built_vector: ^0.1.0
  flutter_secure_storage: ^4.2.0
  dio_http2_adapter: ^2.0.0
  connectivity: ^3.0.6
  flushbar: ^1.10.0
  pretty_dio_logger: ^1.1.1
  url_launcher: ^6.0.9
  geolocator: ^7.3.0
  app_settings: 4.1.1
  location_permissions: ^4.0.0
  airplane_mode_detection: ^1.0.0
  path: ^1.8.0
  lombok: ^0.0.5
  dio: ^4.0.0
  http: ^0.13.3
  mime_type: ^1.0.0
  image_picker: ^0.8.2
  image_cropper: ^1.1.1
  flutter_progress_dialog: ^0.1.0
  flutter_native_image: ^0.0.6+1    #native iOS/Android image resize, compress or crop
  auto_size_text: ^2.1.0
  enum_to_string: ^2.0.1
  modal_progress_hud: ^0.1.3
  openapi_generator_annotations: ^3.2.0
  location: ^4.3.0


  flutter:
    sdk: flutter
  camera:

  flutter_localizations: # add this
    sdk: flutter # add this



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  build_runner: ^2.0.6
  openapi_generator: ^3.2.0+2
  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

  #test: ^1.17.10

flutter_icons:
  android: false
  ios: true
  image_path: "assets/images/app_icon_test.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/gym-placeholder.jpg
    - assets/images/honnold.png
    - assets/images/powered_by_google_on_white2x.png
    - assets/yelp/regular_0@2x.png
    - assets/yelp/regular_1@2x.png
    - assets/yelp/regular_1_half@2x.png
    - assets/yelp/regular_2@2x.png
    - assets/yelp/regular_2_half@2x.png
    - assets/yelp/regular_3@2x.png
    - assets/yelp/regular_3_half@2x.png
    - assets/yelp/regular_4@2x.png
    - assets/yelp/regular_4_half@2x.png
    - assets/yelp/regular_5@2x.png
    - assets/yelp/logo_default@2x.png

  fonts:
    - family: RobotoGoogle
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500

    - family: LatoGoogle
      fonts:
          - asset: assets/fonts/Lato-Regular.ttf
            weight: 500


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
